apiVersion: v1
kind: Secret
metadata:
  name: azure-mysql-secret
  namespace: hospital-system
  labels:
    app: hospital-backend
    database: azure-mysql
type: Opaque
data:
  DB_HOST: <YOUR_DB_HOST>
  DB_USER: <YOUR_DB_USER>
  DB_PASSWORD: <YOUR_DB_PASSWORD>
  DB_NAME: <DB_NAME>
